name: "Pre-Release Build"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-release:
    name: "Pre-Release Build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Github Release"
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: pre-release
