name: "Pre-Release Build"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-release:
    name: "Pre-Release Build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Github Release"
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: pre-release
          name: "Development Build"
          body: ${{ github.event.head_commit.message }}
